[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
# serde
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_yaml = { version = "0" }

# ui
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3" }
log = { version = "0.4" }
wasm-logger = { version = "0.2" }

# rand
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0" }

# cli
clap = { version = "4", features = ["derive"] }

# reactivate
reactivate = { version = "*" }

# api
axum = { version = "0.6" }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1", features = ["full"] }
