[workspace]
members = [
    "run",
    "ai",
    "api",
    "game_of_life",
    "graph",
    "nes",
    "spice",
    "sura",
    "symrs",
    "ui",
    "vultus",
    "yavd",
    "chatgpt",
    "fraction",
    "calc",
    "loc",
    "marker_invariants",
    "random_words",
    "utils",
    "static_assert",
    "sat",
    "threadpool",
    "validation",
]
